In [1]:
import pandas as pd
import numpy as np
import os, re
import matplotlib.pyplot as plt
import nltk
%matplotlib inline

In [2]:
os.chdir(r'D:\Hackathon\How-To-Choose-The-Perfect-Beer-Data-Set')

In [7]:
train_data=pd.read_csv('train_cleaned.csv')
test_data=pd.read_csv('test_cleaned.csv')
train_data.shape, test_data.shape

((185643, 18), (20628, 18))

In [8]:
train_data['glassware_len']=[len(i) for i in train_data['Glassware Used']]
test_data['glassware_len']=[len(i) for i in test_data['Glassware Used']]

In [9]:
train_data.head()

,Unnamed: 0,ABV,Brewing Company,Food Paring,Glassware Used,Beer Name,Ratings,Style Name,Cellar Temperature,Serving Temperature,Score,style_len,min_cellar_temp,max_cellar_temp,min_serving_temp,max_serving_temp,item_score,glass_score,glassware_len
0,0,6.500000,8929,"(Curried,Thai)Cheese(pepperyMontereyPepperJack...","PintGlass(orBecker,Nonic,Tumbler),Mug(orSeidel...",15121,22,AmericanIPA,40-45,45-50,3.28,11,40,45,45,50,3.0,2.0,53
1,1,5.500000,13187,"(PanAsian)Cheese(earthyCamembert,Fontina,nutty...","PintGlass(orBecker,Nonic,Tumbler),Mug(orSeidel...",59817,1,AmericanPaleAle(APA),35-40,40-45,3.52,20,35,40,40,45,4.0,2.0,53
2,2,8.100000,6834,"Meat(Pork,Poultry)","PintGlass(orBecker,Nonic,Tumbler),Mug(orSeidel...",32669,3,IrishRedAle,35-40,40-45,4.01,11,35,40,40,45,1.0,2.0,53
3,3,6.354961,11688,"(Indian,LatinAmerican,PanAsian)General(Aperitif)","PintGlass(orBecker,Nonic,Tumbler),PilsenerGlas...",130798,0,AmericanMaltLiquor,35-40,35-40,0.00,18,35,40,35,40,2.0,3.0,76
4,4,6.000000,10417,"Meat(Poultry,Fish,Shellfish)",PilsenerGlass(orPokal),124087,1,EuroPaleLager,35-40,40-45,2.73,13,35,40,40,45,1.0,1.0,22

In [10]:
test_data.head()

,Unnamed: 0,ABV,Brewing Company,Food Paring,Glassware Used,Beer Name,Ratings,Style Name,Cellar Temperature,Serving Temperature,Score,style_len,min_cellar_temp,max_cellar_temp,min_serving_temp,max_serving_temp,item_score,glass_score,glassware_len
0,0,6.2,8803,"(Curried,Thai)Cheese(pepperyMontereyPepperJack...","PintGlass(orBecker,Nonic,Tumbler),Mug(orSeidel...",34558,3,AmericanIPA,40-45,45-50,NaN,11,40,45,45,50,3.0,2.0,53
1,1,5.3,8558,"(Barbecue)Cheese(butteryBrie,Gouda,Havarti,Swi...","PintGlass(orBecker,Nonic,Tumbler),Mug(orSeidel...",86826,20,AmericanPorter,40-45,45-50,NaN,14,40,45,45,50,4.0,2.0,53
2,2,7.0,7519,"Cheese(earthyCamembert,Fontina)General(Aperitif)","Snifter,Tulip,OversizedWineGlass",17051,0,BelgianDarkAle,45-50,45-50,NaN,14,45,50,45,50,2.0,3.0,32
3,3,5.2,9852,"(LatinAmerican,German)Meat(Pork,Poultry)","Flute,PilsenerGlass(orPokal),Mug(orSeidel,Stein)",49156,2,ViennaLager,35-40,40-45,NaN,11,35,40,40,45,2.0,3.0,48
4,4,8.1,8991,"(Barbecue)Cheese(butteryBrie,Gouda,Havarti,Swi...","PintGlass(orBecker,Nonic,Tumbler),Mug(orSeidel...",162723,5,AmericanPorter,40-45,45-50,NaN,14,40,45,45,50,4.0,2.0,53

In [11]:
train_data.corr()

,Unnamed: 0,ABV,Brewing Company,Beer Name,Ratings,Score,style_len,min_cellar_temp,max_cellar_temp,min_serving_temp,max_serving_temp,item_score,glass_score,glassware_len
Unnamed: 0,1.000000,0.002633,-0.001649,0.000657,-0.001538,0.001272,0.003050,0.002051,0.002035,0.001797,0.001815,-0.000233,-0.000214,-0.003275
ABV,0.002633,1.000000,-0.003046,-0.035403,0.053559,0.130498,0.272474,0.288131,0.271088,0.461440,0.454145,0.029844,0.302961,-0.029127
Brewing Company,-0.001649,-0.003046,1.000000,0.076127,-0.008773,0.013695,0.006882,-0.002084,-0.002075,0.001827,0.001637,0.008090,-0.010165,0.014095
Beer Name,0.000657,-0.035403,0.076127,1.000000,0.002392,-0.006493,-0.031804,-0.005625,-0.005305,-0.014351,-0.014303,0.006230,-0.008086,0.004641
Ratings,-0.001538,0.053559,-0.008773,0.002392,1.000000,0.065293,0.023099,0.022313,0.021319,0.028100,0.027711,-0.007520,0.025692,-0.003466
Score,0.001272,0.130498,0.013695,-0.006493,0.065293,1.000000,0.052274,0.074949,0.070838,0.124193,0.122813,0.036020,0.077039,0.010870
style_len,0.003050,0.272474,0.006882,-0.031804,0.023099,0.052274,1.000000,0.139246,0.134253,0.169907,0.169428,0.057706,0.338820,0.087115
min_cellar_temp,0.002051,0.288131,-0.002084,-0.005625,0.022313,0.074949,0.139246,1.000000,0.999092,0.266265,0.267893,0.224390,0.196104,-0.114746
max_cellar_temp,0.002035,0.271088,-0.002075,-0.005305,0.021319,0.070838,0.134253,0.999092,1.000000,0.234232,0.236626,0.222226,0.183294,-0.112463
min_serving_temp,0.001797,0.461440,0.001827,-0.014351,0.028100,0.124193,0.169907,0.266265,0.234232,1.000000,0.999126,0.101435,0.290187,-0.057344
max_serving_temp,0.001815,0.454145,0.001637,-0.014303,0.027711,0.122813,0.169428,0.267893,0.236626,0.999126,1.000000,0.103516,0.289378,-0.052126
item_score,-0.000233,0.029844,0.008090,0.006230,-0.007520,0.036020,0.057706,0.224390,0.222226,0.101435,0.103516,1.000000,-0.007843,0.018311
glass_score,-0.000214,0.302961,-0.010165,-0.008086,0.025692,0.077039,0.338820,0.196104,0.183294,0.290187,0.289378,-0.007843,1.000000,0.404076
glassware_len,-0.003275,-0.029127,0.014095,0.004641,-0.003466,0.010870,0.087115,-0.114746,-0.112463,-0.057344,-0.052126,0.018311,0.404076,1.000000

In [42]:
train_data_final=train_data.drop(labels=['Unnamed: 0','Brewing Company','max_cellar_temp',\
                                        'max_serving_temp','glassware_len','Food Paring','Glassware Used','Style Name',\
                                        'Cellar Temperature','Serving Temperature'], axis=1)
test_data_final=test_data.drop(labels=['Unnamed: 0','Brewing Company','max_cellar_temp',\
                                        'max_serving_temp','glassware_len','Food Paring','Glassware Used','Style Name',\
                                        'Cellar Temperature','Serving Temperature'], axis=1)

In [43]:
train_data_final.head()

,ABV,Beer Name,Ratings,Score,style_len,min_cellar_temp,min_serving_temp,item_score,glass_score
0,6.500000,15121,22,3.28,11,40,45,3.0,2.0
1,5.500000,59817,1,3.52,20,35,40,4.0,2.0
2,8.100000,32669,3,4.01,11,35,40,1.0,2.0
3,6.354961,130798,0,0.00,18,35,35,2.0,3.0
4,6.000000,124087,1,2.73,13,35,40,1.0,1.0

In [44]:
train_data_final.corr()

,ABV,Beer Name,Ratings,Score,style_len,min_cellar_temp,min_serving_temp,item_score,glass_score
ABV,1.000000,-0.035403,0.053559,0.130498,0.272474,0.288131,0.461440,0.029844,0.302961
Beer Name,-0.035403,1.000000,0.002392,-0.006493,-0.031804,-0.005625,-0.014351,0.006230,-0.008086
Ratings,0.053559,0.002392,1.000000,0.065293,0.023099,0.022313,0.028100,-0.007520,0.025692
Score,0.130498,-0.006493,0.065293,1.000000,0.052274,0.074949,0.124193,0.036020,0.077039
style_len,0.272474,-0.031804,0.023099,0.052274,1.000000,0.139246,0.169907,0.057706,0.338820
min_cellar_temp,0.288131,-0.005625,0.022313,0.074949,0.139246,1.000000,0.266265,0.224390,0.196104
min_serving_temp,0.461440,-0.014351,0.028100,0.124193,0.169907,0.266265,1.000000,0.101435,0.290187
item_score,0.029844,0.006230,-0.007520,0.036020,0.057706,0.224390,0.101435,1.000000,-0.007843
glass_score,0.302961,-0.008086,0.025692,0.077039,0.338820,0.196104,0.290187,-0.007843,1.000000

In [45]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

y=train_data_final['Score']
X=train_data_final.drop(labels=['Score'], axis=1)

# Split the train data to train-test split
X_train, X_test, y_train, y_test=train_test_split(X, y, train_size=0.8, random_state=45)

# Training model object
regressor=LinearRegression()
model_obj=regressor.fit(X_train, y_train)
y_pred=model_obj.predict(X_test)
y_act=y_test
mean_abs_err=mean_absolute_error(y_act, y_pred)
mean_sqr_err=mean_squared_error(y_act, y_pred)

print('Mean absolute error: ', mean_abs_err)
print('Mean squared error: ', mean_sqr_err)

Mean absolute error:  0.946691770130299
Mean squared error:  1.7808733144153728

C:\Users\Arunachalam\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [46]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

y=train_data_final['Score']
X=train_data_final.drop(labels=['Score'], axis=1)

# Split the train data to train-test split
X_train, X_test, y_train, y_test=train_test_split(X, y, train_size=0.8, random_state=45)

# Training model object
regressor=RandomForestRegressor()
model_obj=regressor.fit(X_train, y_train)
y_pred=model_obj.predict(X_test)
y_act=y_test
mean_abs_err=mean_absolute_error(y_act, y_pred)
mean_sqr_err=mean_squared_error(y_act, y_pred)

print('Mean absolute error: ', mean_abs_err)
print('Mean squared error: ', mean_sqr_err)

C:\Users\Arunachalam\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

Mean absolute error:  0.2604338098655295
Mean squared error:  0.14968015399316678

In [47]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

y=train_data_final['Score']
X=train_data_final.drop(labels=['Score'], axis=1)

# Split the train data to train-test split
X_train, X_test, y_train, y_test=train_test_split(X, y, train_size=0.8, random_state=45)

# Training model object
regressor=GradientBoostingRegressor()
model_obj=regressor.fit(X_train, y_train)
y_pred=model_obj.predict(X_test)
y_act=y_test
mean_abs_err=mean_absolute_error(y_act, y_pred)
mean_sqr_err=mean_squared_error(y_act, y_pred)

print('Mean absolute error: ', mean_abs_err)
print('Mean squared error: ', mean_sqr_err)

C:\Users\Arunachalam\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

Mean absolute error:  0.251148834207295
Mean squared error:  0.13461427181186653

In [48]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

y=train_data_final['Score']
X=train_data_final.drop(labels=['Score'], axis=1)

# Split the train data to train-test split
X_train, X_test, y_train, y_test=train_test_split(X, y, train_size=0.8, random_state=45)

# Training model object
regressor=XGBRegressor()
model_obj=regressor.fit(X_train, y_train)
y_pred=model_obj.predict(X_test)
y_act=y_test
mean_abs_err=mean_absolute_error(y_act, y_pred)
mean_sqr_err=mean_squared_error(y_act, y_pred)

print('Mean absolute error: ', mean_abs_err)
print('Mean squared error: ', mean_sqr_err)

C:\Users\Arunachalam\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

Mean absolute error:  0.25075279246194276
Mean squared error:  0.13404092703400236

### Grid Search - GBM

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.grid_search import GridSearchCV
param_test1 = {'n_estimators':[50, 100, 300], 'min_samples_leaf':[10, 50, 70], ''}

gbm = GradientBoostingClassifier(learning_rate=0.1, min_samples_split=500,min_samples_leaf=50,max_depth=8,\
                                 max_features='sqrt',subsample=0.8,random_state=10)

gsearch1 = GridSearchCV(estimator=gbm, param_grid = param_test1, scoring='roc_auc',n_jobs=4,iid=False, cv=5)

gsearch1.fit(X_train, y_train.values.ravel())
gsearch1.grid_scores_, gsearch1.best_params_, gsearch1.best_score_